name: Resume Generator
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - id: render-html
        name: Render JSON Resume HTML
        uses: chessmango/action-resumed-render@v1.1.1
        with:
          theme: jsonresume-theme-even
          input_file: resume.json
          output_file: index.html
      # - id: render-pdf
      #   name: Render JSON Resume PDF
      #   uses: fifsky/html-to-pdf-action@v0.1.0
      #   with:
      #     htmlFile: index.html
      #     outputFile: resume.pdf
      #     pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Create release for tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./resume.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Resume
          branch: master
          file_pattern: resume.pdf index.html
          status_options: '--untracked-files=no'
